domain_pattern: !ruby/regexp '/.*\.sg\.vivowares\.vpc/'
dns_log: tmp/logs/dns.log
http_log: tmp/logs/http.log
god_log: tmp/logs/god.log
lookup: lookup.json
downstream:
  host: 0.0.0.0
  tcp: 5300
  udp: 5300
  http: 5301
upstream:
  host: 8.8.8.8
  tcp: 53
  udp: 53
